// SaaS价格数据库 - 根据slug匹配行业平均月费
export const SAAS_PRICES = {
  'convert-curl-to-axios': 29,
  'optimize-react-performance': 49,
  'secure-api-keys': 39,
  'responsive-design-tips': 19,
  'javascript-async-await': 0,
  'css-grid-layout': 29,
  'nodejs-performance': 79,
  'serverless-architecture': 99,
  'accessibility-testing': 49,
  'microservices-architecture': 149,
  'graphql-api-design': 79,
  'rest-api-best-practices': 0,
  'docker-containerization': 49,
  'kubernetes-deployment': 199,
  'ci-cd-pipeline': 99,
  'testing-jest': 0,
  'code-quality': 29,
  'error-handling': 0,
  'web-vitals': 49,
  'dependency-management': 19,
  'form-validation': 0,
  'authentication-strategies': 79,
  'api-documentation': 29,
  'database-optimization': 99,
  'caching-strategies': 49,
  'security-best-practices': 79,
  'performance-monitoring': 99,
  'logging-debugging': 29,
  'code-refactoring': 0,
  'typescript-advanced': 49,
  'react-hooks-patterns': 29,
  'state-management': 49,
  'api-integration': 39,
  'web-sockets': 59,
  'file-upload-handling': 29,
  'email-integration': 19,
  'payment-integration': 99,
  'search-implementation': 79,
  'analytics-tracking': 49,
  'seo-optimization': 39,
  'pwa-development': 29,
  'mobile-responsive': 19,
  'animation-libraries': 29,
  'chart-visualization': 49,
  'map-integration': 79,
  'video-streaming': 149,
  'audio-processing': 99,
  'image-optimization': 29,
  'pdf-generation': 39,
  'excel-export': 49,
  'calendar-scheduling': 59,
  'chat-messaging': 79,
  'notification-system': 49,
  'user-management': 99,
  'role-permissions': 79,
  'audit-logging': 59,
  'backup-recovery': 99,
  'multi-tenancy': 199,
  'localization': 49,
  'accessibility-compliance': 79,
  'gdpr-compliance': 99,
  'performance-audit': 49,
  'security-audit': 149,
  'code-review': 99,
  'documentation-generation': 29,
  'api-testing': 49,
  'load-testing': 99,
  'integration-testing': 79,
  'e2e-testing': 99,
  'unit-testing': 0,
  'code-coverage': 49,
  'debugging-tools': 29,
  'profiling-tools': 79,
  'memory-leak-detection': 99,
  'bundle-optimization': 49,
  'lazy-loading': 0,
  'code-splitting': 0,
  'tree-shaking': 0,
  'image-compression': 19,
  'video-compression': 49,
  'cdn-integration': 79,
  'dns-optimization': 29,
  'ssl-certificates': 0,
  'firewall-configuration': 99,
  'ddos-protection': 199,
  'backup-automation': 79,
  'disaster-recovery': 299,
  'monitoring-alerts': 99,
  'log-aggregation': 149,
  'error-tracking': 79,
  'performance-metrics': 99,
  'user-analytics': 49,
  'ab-testing': 99,
  'feature-flags': 79,
  'configuration-management': 49,
  'secrets-management': 99,
  'key-rotation': 79,
  'certificate-management': 99,
  'vulnerability-scanning': 149,
  'penetration-testing': 299,
  'compliance-reporting': 199,
  'data-encryption': 99,
  'simple-client-database-law-firm-no-subscription': 100,
  'offline-inventory-tracker-small-bakery': 50,
  'replace-typeform-self-hosted-html': 50,
  'affiliate-link-manager-niche-bloggers': 30,
  'pet-health-record-tracker-no-cloud': 20,
  'warehouse-bin-locator-small-ecommerce': 80,
  'collect-testimonials-no-monthly-fee': 30,
  'volunteer-hour-tracker-no-sub': 40,
  'small-school-library-tracker': 60,
  'barbershop-walk-in-list': 25,
  'car-wash-membership-tracker': 35,
  'wedding-rsvp-tracker-no-fee': 45,
  'flea-market-sales-log': 15,
  'embroidery-pattern-tracker': 20,
  'community-tool-rental-log': 30,
  'therapy-session-notes-solo': 70,
  'vinyl-record-collection-tracker': 25,
  'coffee-loyalty-card-no-app': 30,
  'aquarium-water-quality-log': 20,
  'craft-fair-booth-planner': 35,
  'bike-maintenance-tracker-no-sub': 25,
  'scholarship-application-tracker': 40,
  'campsite-review-log-vanlife': 30,
  'bee-hive-inspection-log': 35,
  'home-brewery-batch-tracker': 40,
  'choir-attendance-tracker': 25,
  'garden-seed-starter-log': 20,
  'ham-radio-logbook-no-saas': 30,
  'meditation-minutes-tracker-no-sync': 15
};

// 分类价格映射
export const CATEGORY_PRICES = {
  'development': 49,
  'database': 99,
  'security': 79,
  'performance': 69,
  'testing': 49,
  'monitoring': 99,
  'default': 50
};

// 获取SaaS价格
export function getSaaSPrice(slug) {
  if (SAAS_PRICES[slug] !== undefined) {
    return SAAS_PRICES[slug];
  }
  
  for (const [key, price] of Object.entries(CATEGORY_PRICES)) {
    if (slug.includes(key)) {
      return price;
    }
  }
  
  return CATEGORY_PRICES.default;
}
